# -*- coding: utf-8 -*-
"""
/***************************************************************************
 frz_button
                                 A QGIS plugin
 Este plugin cria zonas de restrição de voo para drones
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-21
        copyright            : (C) 2025 by Edson Tadeu da Silva Pinto
        email                : e.tadeu.eb@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):  # pylint: disable=invalid-name
    from .frz_button import frzPlugin
    return frzPlugin(iface)
